### ISSUE TITLE
Another variant on this project

### ISSUE THREAD

**Issue by mschipperheyn** [DanielHreben/sequelize-transparent-cache#48]
Hey, I lost track of this project a long while ago and based my own implementation on the original code base. I have moved to Graphql and my version has a number of features geared towards dealing with the "dataloader" concept that is common in that field. I'm wondering if there is any way I can contribute?

My own version has some additions that I don't see here:
- The ability to get a cached association on an instance
- The ability to clear cache keys based on a regular expression
- The ability to hash a where statement 

What I implemented assumes basically: 
- people retrieve lists and individual objects
- lists have pagination and other where specific aspects
- you need to be able to clean the cache in a smart way. Update object x, and all the related list elements need to be cleaned as well. 

In order to achieve this for lists, I basically define a cache key, e.g. `list`. and add any where statement as an add on hash, e.g. `list%some_hash%`. And when I update an individual row, in addition to cleaning the item, I clean `list` using a regular expression. I also offer a debug output to help in the debugging.

It makes the cache powerful but also leads to some fragility because you can get unexpected issues if you don't know what you're doing. But it would be nice to attempt to abstract this logic to a level that anyone could use it confidently.

**Comment by DanielHreben** [comment]
Hi! Currently, this lib has support for caching arbitrary `where` statements (maybe I should highlight it better in docs?). The only limitation - you should care about invalidation, and do it manually when it's time. The whole result of `where` statement is cached in a single record, so you can only invalidate it completely. 
An approach that you described, seems a bit weird to me, you basically trying to implement database on top of cache system, and keep this database in sync with the main database. Can you describe a practical reason to do it? Which cache system are you using? How is your invalidation by regexp works? Seems like it should scan all keys (unless you also implemented indexes on top of cache ;) )

**Comment by mschipperheyn** [comment]
I'm using Redis and the practical reason is performance.

**Comment by mschipperheyn** [comment]
The validation expiration  works basically as follows.
E.g. you have a list, with various where and pagination options:
The cache key will be `list`. The lib will hash the the where statement etc into a hash which is added to `list%xyz-hash%`. xyz-hash being the generated hash.
When you update item x that is part of the list, the regex selects all keys that start with `list` and removes them.

**Comment by DanielHreben** [comment]
Ok, so how is your Redis commands look like?
I'm asking because KEYS and SCAN commands in Redis is not supposed to be used like this.

**Comment by mschipperheyn** [comment]
```
	scan(pattern) {
		const wildcardPattern = `${this.withNamespace(pattern)}*`;
		debugIO(`Scan cache pattern: ${wildcardPattern}`);
		return scan(this.client, '0', wildcardPattern, new Set());
	}
```

**Comment by DanielHreben** [comment]
From SCAN command documentation:
> It is important to note that the MATCH filter is applied after elements are retrieved from the collection, just before returning data to the client. 

Which means, with this approach you iterating through all keys in your redis every time you need to remove something. Since redis single-threaded - it blocks all other operations with it. This is very opposite to the goal - get more performance. It should be easy to prove with benchmarks.

**Comment by mschipperheyn** [comment]
@DanielHreben Good to know! Thanks for the head's up

**Comment by DanielHreben** [comment]
@mschipperheyn sorry, there is NO prefix. Please read a quote from SCAN documentation again. You literally iterating through ALL elements in your cache EVERY time.

**Comment by mschipperheyn** [comment]
@DanielHreben hmm, I read that differently. That would be horrible.

**Comment by mschipperheyn** [comment]
Sounds like I may need the KEYS command with a wildcard as an alternative.

**Comment by DanielHreben** [comment]
Same problem with KEYS. Cache systems are not like database systems, they don't support indexes and searches.

**Comment by mschipperheyn** [comment]
Hmm, yeah, I see the trade off here: https://stackoverflow.com/questions/39273601/redis-scan-match-performance-with-large-number-of-keys 

There seem to be some others who have looked at this issue and optimized it. https://morganwu277.github.io/2017/07/16/Django-Redis-Scan-Too-Long/

SCAN was prob the best option provided it implements like in the link. But it's worth reconsidering the trade offs.

**Comment by mschipperheyn** [comment]
And there is this: https://github.com/luin/ioredis/blob/a170ac7e95e01ab20e3ccdba0abcd437fb17c90e/README.md#streamify-scaning Thanks for all the head's up!

**Comment by DanielHreben** [comment]
You are welcome!

In short, there are 2 ways to find a list of keys:
* **KEYS or SCAN with no limit** - relatively fast, but block all other operations
* **SCAN with limit** - by splitting large operation into chanks of smaller operations you not blocking other operations for a while. But this is relatively slow, and during this cleanup data in your cache will be in an inconsistent state. 

Both options are not acceptable for most cases in production. 

This is very simplified vision of the problem, and I'm not mentioning lots of other problems that you face with the approach you trying to implement. My advice - review your caching strategy, and not try to implement a database system on top of the cache system. 
Probably you can just use this library since now we support arbitrary `where` statements, or maybe you just need to add read-replica you database and use it instead of adding cache. Or maybe you don't need any of these tricks at all (premature optimization?), databases are actually really fast, just make sure you using right indexes.
